name: "Provenance generator"
description: "Generate provenance for a binary in GitHub Actions"
inputs:
  binary:
    description: "the path to the binary built"
    required: true
  github_token:
    description: 'GitHub API Token'
    required: true
outputs:
  provenance:
    description: "The JSON string of the provenance produced"
runs:
  using: "composite"
  steps:
    - uses: 'actions/download-artifact@v2'
      with:
        name: ${{ inputs.binary }}
    - name: Set env
      run: | 
        echo "digest=$(sha256sum ${{ inputs.binary }} | awk '{print $1}')" >> $GITHUB_ENV
      shell: bash
    # Checkout for local action
    - uses: actions/checkout@v2.4.0
    - uses: './slsa-provenance/generator'
      id: provenance
      with:
        digest: ${{ env.digest }}
        token: ${{ inputs.github_token }}
    - name: Set provenance output
      run: | 
        echo '::set-output name=provenance::${{ steps.provenance.outputs.provenance }}'
      shell: bash
