name: goreleaser slsa 3 composite action

description: 'goreleaser slsa 3 composite action'

inputs:
  # BYOB-provided inputs
  slsa-workflow-inputs:
    # Inputs in JSON format.
    description: 'All the onputs'
    type: string
    required: true
  slsa-layout-file:
    description: 'Location to store the layout content'
    type: string
    required: true


outputs:
  # Outputs from the inner GitHub Action call.
  some-output:
    description: "some output"
    value: ${{ steps.generate-outputs.outputs.some-output }}
  other-output:
    description: "other output"
    value: ${{ steps.generate-outputs.outputs.other-output }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # v2.2.0
      with:
        go-version: 1.19 # argument to the Action.
        check-latest: true

    - name: run goreleaser
      id: goreleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        args: release --rm-dist

      #uses: ./../__TOOL_CHECKOUT_DIR__

    - name: after goreleaser
      shell: bash
      run: |
        echo done!
        echo "hello, world" > result.txt

    - name: Upload result
      id: upload
      uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # tag=v3.1.1
      with:
        name: "result.txt"
        path: "result.txt"

    - name: "run"
      id: generate-outputs
      env:
        SLSA_OUTPUTS_ARTIFACTS_FILE: ${{ inputs.slsa-layout-file }}
      shell: bash
      run: |
        hash=$(sha256sum result.txt | awk '{print $1}')
        echo 
        echo "SLSA_OUTPUTS_ARTIFACTS_FILE: $SLSA_OUTPUTS_ARTIFACTS_FILE"
        cat <<EOF >DATA
        {
          "version": 1,
          "attestations": [
            {
              "name": "attestation1.intoto",
              "subjects": [
                { "name": "result.txt",
                  "digest": { "sha256": "853ff93762a06ddbf722c4ebe9ddd66d8f63ddaea97f521c3ecc20da7c976020" }},
                { "name": "artifact12",
                  "digest": { "sha256": "d4d5899a3868fbb6ae1856c3e55a32ce35913de3956d1973caccd37bd0174fa2" }}
                ]
            },
            {
              "name": "attestation2.intoto",
              "subjects": [
                { "name": "artifact21",
                  "digest": { "sha256": "0ded0808c4d85f2ee0db86980ae610cc9d165e9ca9da466196cc73c346513713" }},
                { "name": "artifact22",
                  "digest": { "sha256": "e363cc5b4e500bfc727106434a2578b38440aa18e105d57576f3d8f2abebf888" }}
                ]
            }
          ]
        }
        EOF
        #TODO: output in file and base64 -w0
        # NOTE: we relay the output from the inner Action.
        echo "some-output=tool-defined-some-output" >> "$GITHUB_OUTPUT"
        echo "other-output=tool-defined-other-output" >> "$GITHUB_OUTPUT"
        # Expected file with pre-defined output
        cat DATA > "$SLSA_OUTPUTS_ARTIFACTS_FILE"