name: goreleaser slsa 3 composite action

description: 'goreleaser slsa 3 composite action'

inputs:
  # BYOB-provided inputs
  slsa-workflow-inputs:
    # Inputs in JSON format.
    description: 'All the onputs'
    type: string
    required: true
  slsa-layout-file:
    description: 'Location to store the layout content'
    type: string
    required: true


outputs:
  # Outputs from the inner GitHub Action call.
  artifacts:
    description: "build artifacts"
    value: ${{ steps.goreleaser.outputs.artifacts }}
  metadata:
    description: "build metadata"
    value: ${{ steps.goreleaser.outputs.metadata }}

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # v2.2.0
      with:
        go-version: 1.19 # argument to the Action.
        check-latest: true

    - name: run goreleaser
      id: goreleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        args: release --rm-dist

    - name: after goreleaser
      shell: bash
      run: |
        echo done!
        echo "hello, world" > result.txt

    - name: Upload result
      id: upload
      uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # tag=v3.1.1
      with:
        name: goreleaser
        path: dist/*

    - name: "run"
      id: generate-outputs
      env:
        SLSA_OUTPUTS_ARTIFACTS_FILE: ${{ inputs.slsa-layout-file }}
      shell: bash
      run: |
        path=$(cat outputs.json | jq -r .[0].path)
        base=$(basename $path)
        hash=$(sha256sum $path | awk '{print $1}')
        echo 
        echo "SLSA_OUTPUTS_ARTIFACTS_FILE: $SLSA_OUTPUTS_ARTIFACTS_FILE"
        cat <<EOF >DATA
        {
          "version": 1,
          "attestations": [
            {
              "name": "attestation.intoto",
              "subjects": [
                { "name": "$base",
                  "digest": { "sha256": "$hash" }}
                ]
            }
          ]
        }
        EOF
        #TODO: output in file and base64 -w0
        # NOTE: we relay the output from the inner Action.
        echo "some-output=tool-defined-some-output" >> "$GITHUB_OUTPUT"
        echo "other-output=tool-defined-other-output" >> "$GITHUB_OUTPUT"
        # Expected file with pre-defined output
        cat DATA > "$SLSA_OUTPUTS_ARTIFACTS_FILE"