name: SLSA go builder

permissions:
  contents: read

env:
  #TODO: let caller upload ?
  REGISTRY: ghcr.io
  BUILDER_BINARY: builder
  PROVENANCE_BINARY: provenance
  BUILDER_REPOSITORY: asraa/slsa-on-github
  BUILDER_REF: test-prov

###################################################################
#                                                                 #
#            Input and output argument definitions                #
#                                                                 #
###################################################################
on:
  workflow_call:
    inputs:
      go-version:
        description: "The go version to use"
        required: true
        type: string
      upload-location:
        description: "Upload registry location"
        required: false
        type: string
        default: "$REGISTRY/${{ github.repository }}"
      env:
        description: "Env variables to pass to the builder"
        required: false
        type: string
    outputs:
      go-binary-name:
        description: "The name of the generated binary uploaded to the artifact registry"
        value: ${{ jobs.build.outputs.go-binary-name }}

jobs:
  builder:
    outputs:
      go-builder-sha256: ${{ steps.builder-gen.outputs.go-builder-sha256 }}
      go-prov-sha256: ${{ steps.builder-gen.outputs.go-prov-sha256 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.3.4
        with:
          fetch-depth: 0
          repository: "${{ env.BUILDER_REPOSITORY }}"
          ref: "${{ env.BUILDER_REF }}"

      - name: Set up golang environment
        uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 # v2.1.3
        with:
          go-version: 1.17

      - name: Download dependencies
        shell: bash
        run: |
          set -euo pipefail
          #TODO(reproducible)
          cd build-go
          go mod vendor
          cd -
          cd slsa-provenance
          go mod vendor
          cd -

      # TODO(hermeticity) OS-level.
      # - name: Disable hermeticity
      # uses: slsa/hermeticity@xxx
      #   with:
      #     to-state: enabled

      - name: Build builder
        shell: bash
        id: builder-gen
        env:
          BUILDER_BINARY: "${{ env.BUILDER_BINARY }}"
          PROVENANCE_BINARY: "${{ env.PROVENANCE_BINARY }}"
        run: |
            set -euo pipefail
            cd build-go
            # https://go.dev/ref/mod#build-commands.
            go build -mod=vendor -o "$BUILDER_BINARY"
            BUILDER_DIGEST=$(sha256sum "$BUILDER_BINARY" | awk '{print $1}')
            echo "::set-output name=go-builder-sha256::$BUILDER_DIGEST"
            echo "hash of $BUILDER_BINARY is $BUILDER_DIGEST"
            cd -
            cd slsa-provenance
            go build -mod=vendor -o "$PROVENANCE_BINARY"
            PROVENANCE_DIGEST=$(sha256sum "$PROVENANCE_BINARY" | awk '{print $1}')
            echo "::set-output name=go-prov-sha256::$PROVENANCE_DIGEST"
            echo "hash of $PROVENANCE_BINARY is $PROVENANCE_DIGEST"

      - name: Upload the builder
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: "${{ env.BUILDER_BINARY }}"
          path: "build-go/${{ env.BUILDER_BINARY }}"
          retention-days: 5
      - name: Upload the provenance binary
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: "${{ env.PROVENANCE_BINARY }}"
          path: "slsa-provenance/${{ env.PROVENANCE_BINARY }}"
          retention-days: 5

  build:
    outputs:
      go-binary-sha256: ${{ steps.sha256-gen.outputs.go-binary-sha256 }}
      go-binary-name: ${{ steps.build-gen.outputs.go-binary-name }}
    runs-on: ubuntu-latest
    needs: builder
    steps:
      - name: Checkout the repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.3.4
        with:
          fetch-depth: 0

      # Code needed (not tested) if go-vesion is made optional.
      # See https://stackoverflow.com/questions/67368005/check-whether-environment-variable-is-empty.
      - name: Set up golang environment
        uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 # v2.1.3
        with:
          go-version: ${{ inputs.go-version }}

      - name: Download builder
        uses: actions/download-artifact@v2
        with:
          name: "${{ env.BUILDER_BINARY }}"

      - name: Download provenance
        uses: actions/download-artifact@v2
        with:
          name: "${{ env.PROVENANCE_BINARY }}"

      - name: Verify builder and provenance
        env:
          BUILDER_HASH: "${{ needs.builder.outputs.go-builder-sha256 }}"
          BUILDER_BINARY: "${{ env.BUILDER_BINARY }}"
          PROV_HASH: "${{ needs.builder.outputs.go-prov-sha256 }}"
          PROVENANCE_BINARY: "${{ env.PROVENANCE_BINARY }}"
        run: |
          set -euo pipefail

          echo "hash of builder should be $BUILDER_HASH"
          COMPUTED_HASH=$(sha256sum "$BUILDER_BINARY" | awk '{print $1}')
          echo "builder hash computed is $COMPUTED_HASH"

          # Compare hashes. Explicit exit to be safe.
          # TODO: remove the builder as well.
          echo "$BUILDER_HASH $BUILDER_BINARY" | sha256sum --strict --check --status || exit -2

          echo "hash of provenance generator should be $PROV_HASH"
          PROV_HASH=$(sha256sum "$PROVENANCE_BINARY" | awk '{print $1}')
          echo "provenance generator hash computed is $PROV_HASH"

          # Compare hashes. Explicit exit to be safe.
          # TODO: remove the provenance generator as well.
          echo "$PROV_HASH $PROVENANCE_BINARY" | sha256sum --strict --check --status || exit -2
    
          # Make the builder and provenance generator executable.
          chmod a+x "$PROVENANCE_BINARY" "$BUILDER_BINARY"

      - name: Download dependencies
        shell: bash
        run: |
          set -euo pipefail
          go mod vendor

      # TODO(hermeticity) OS-level.
      # - name: Disable hermeticity
      # uses: slsa/hermeticity@xxx
      #   with:
      #     to-state: enabled

      - name: Build project
        id: build-gen
        shell: bash
        env:
          BUILDER_BINARY: "${{ env.BUILDER_BINARY }}"
          PROVENANCE_BINARY: "${{ env.PROVENANCE_BINARY }}"
          UNTRUSTED_ENVS: "${{ inputs.env }}"
          UNTRUSTED_WORKING_DIR: "${{ inputs.working-dir }}"
        run: |
          set -euo pipefail

          # TODO: pass UNTRUSTED_WORKING_DIR to builder, which will use realpath()
          # to compute the actual directory.
          echo "./$BUILDER_BINARY" ./releaser.yml "$UNTRUSTED_ENVS"
          ./"$BUILDER_BINARY" ./releaser.yml "$UNTRUSTED_ENVS"

      - name: Hash of project binary
        id: sha256-gen
        shell: bash
        env:
          UNTRUSTED_BINARY_NAME: "${{ steps.build-gen.outputs.go-binary-name }}"
        run: |
          set -euo pipefail

          echo "completed build"

          # TODO: digest and names will be returned by the builder using info from config file.
          DIGEST=$(sha256sum "$UNTRUSTED_BINARY_NAME" | awk '{print $1}')
          echo "::set-output name=go-binary-sha256::$DIGEST"

          # Get provenance
          # echo "GITHUB_CONTEXT=${{ toJSON(github) }} ./$PROVENANCE_BINARY"
          export GITHUB_CONTEXT=${{ toJSON(github) }}
          ./"$PROVENANCE_BINARY" 

      #TODO(upload): verify how the action handles malicious names.
      - name: Upload the artifact
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: ${{ steps.build-gen.outputs.go-binary-name }}
          path: ${{ steps.build-gen.outputs.go-binary-name }}
          retention-days: 5

  provenance:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      # package should be removed and done by caller.
      # packages: write
      contents: read
    steps:
      - name: Log in to the GitHub Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # sign binary and provenance and upload to Container registry
      - uses: sigstore/cosign-installer@main
      - name: Sign the binary blog with cosign
        id: cosignid
        env:
          COSIGN_EXPERIMENTAL: "true"
          # Note: binary name is not verified
          UNTRUSTED_BINARY_NAME: ${{ steps.build-gen.outputs.go-binary-name }}
        run: |
          set -euo pipefail
          echo cosign upload blob -f "$UNTRUSTED_BINARY_NAME" ghcr.io/asraa/slsa-github-demo
          echo cosign sign-blob ghcr.io/asraa/slsa-github-demo
          echo "::set-output name=go-binary-signature::$UNTRUSTED_SIGNED_BINARY_NAME"

      - name: Upload the signed artifact and provenance
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: ${{ steps.cosignid.outputs.go-binary-signature }}
          path: ${{ steps.cosignid.outputs.go-binary-name }}
          retention-days: 5
