name: Reusable workflow

permissions: read-all

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
    # Map the workflow outputs to job outputs
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.example_job.outputs.output2 }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      steps:
      - name: Checkout the repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.3.4
        with:
          fetch-depth: 0
      # Code needed (not tested) if go-vesion is made optional.
      # See https://stackoverflow.com/questions/67368005/check-whether-environment-variable-is-empty.
      - name: Set up golang environment
        uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 # v2.1.3
        with:
          go-version: ${{ inputs.go-version }}
      
      # TODO(hermeticity)
      # - name: Enable hermeticity
      # uses: slsa/hermeticity@xxx
      #   with:
      #     to-state: enabled

      - name: Download dependencies
        shell: bash
        run: |
          go mod vendor
      
      # TODO(hermeticity)
      # - name: Disable hermeticity
      # uses: slsa/hermeticity@xxx
      #   with:
      #     to-state: disabled

      - name: Build project
        shell: bash
        run: |
          go build -o SLSA_BINARY

      #TODO(upload): verify how the action handles malicious names.
      - name: Upload the artifact
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: SLSA_BINARY
          path: SLSA_BINARY
          retention-days: 5
      # - uses: ./.github/actions/build-go
      #   with:
      #     go-version: ${{ inputs.go-version }}

  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
    steps:
      - id: step1
        run: echo "::set-output name=firstword::hello"
      - id: step2
        run: echo "::set-output name=secondword::world"